import assert from 'node:assert/strict';
import { Game } from './game.mjs';

const game = new Game();
assert.equal(game.soldierCount, Infinity);
assert.equal(game.has(-1_000_000_000, 1_000_000_000), true);
assert.equal(game.has(1_000_000_000, -1), false);
assert.equal(game.has(0.5, 0), false);
assert.deepEqual(game.legalMoves(0, 1), [{ x: 0, y: -1 }]);
assert.equal(game.move(0, 1, 0, -1), true);
assert.equal(game.has(0, 1), false);
assert.equal(game.has(0, 0), false);
assert.equal(game.has(0, -1), true);
assert.equal(game.moves, 1);
assert.equal(game.progress, 1);
assert.equal(game.updateLine(), true);
assert.equal(game.line, -1);
assert.equal(game.progress, 0);
assert.equal(game.undo(), true);
assert.equal(game.line, 0);
assert.equal(game.progress, 1);
assert.equal(game.undo(), true);
assert.equal(game.moves, 0);
assert.equal(game.cells.size, 0);
assert.equal(game.redo(), true);
assert.equal(game.redo(), true);
assert.equal(game.line, -1);
assert.equal(game.moves, 1);
assert.equal(game.canRedo, false);
game.undo();
game.toggle(-1234, -50);
assert.equal(game.canRedo, false);
assert.equal(game.progress, 50);

for (const [dx, dy] of [[0, -2], [2, 0], [0, 2], [-2, 0]]) {
  const board = new Game();
  board.clear();
  const x = -1_000_000_000;
  const y = -2_000_000_000;
  board.toggle(x, y);
  board.toggle(x + dx / 2, y + dy / 2);
  assert.deepEqual(board.legalMoves(x, y), [{ x: x + dx, y: y + dy }]);
  assert.equal(board.move(x, y, x + dx, y + dy), true);
  assert.equal(board.has(x, y), false);
  assert.equal(board.has(x + dx / 2, y + dy / 2), false);
  assert.equal(board.has(x + dx, y + dy), true);
  assert.equal(board.soldierCount, 1);
  assert.equal(board.undo(), true);
  assert.equal(board.soldierCount, 2);
  assert.equal(board.moves, 0);
  assert.equal(board.redo(), true);
  assert.equal(board.moves, 1);
}

const sparse = new Game();
sparse.clear();
assert.equal(sparse.progress, 0);
assert.equal(sparse.updateLine(), false);
sparse.toggle(0, 0);
sparse.toggle(1, 0);
for (const destination of [[1, 0], [1, 1], [2, 2], [3, 0], [0, -2]]) {
  assert.equal(sparse.move(0, 0, ...destination), false);
}
assert.equal(sparse.move(2, 0, 0, 0), false);
assert.equal(sparse.move(0, 0, NaN, 0), false);
assert.equal(sparse.toggle(Infinity, 0), false);
assert.equal(sparse.toggle(Number.MAX_SAFE_INTEGER + 1, 0), false);
assert.equal(sparse.toggle(1.5, 0), false);
assert.equal(sparse.soldierCount, 2);
sparse.toggle(2, 0);
assert.equal(sparse.move(0, 0, 2, 0), false);
sparse.toggle(2, 0);
assert.equal(sparse.move(0, 0, 2, 0), true);
sparse.toggle(1_000_000_000, -1_000_000_000);
sparse.updateLine();
assert.equal(sparse.line, -1_000_000_000);
assert.equal(sparse.progress, 0);
const snapshot = { base: sparse.base, cells: new Set(sparse.cells), moves: sparse.moves, line: sparse.line };
assert.equal(sparse.clear(), true);
assert.equal(sparse.soldierCount, 0);
assert.equal(sparse.moves, 0);
assert.equal(sparse.line, 0);
assert.equal(sparse.undo(), true);
assert.equal(sparse.base, snapshot.base);
assert.deepEqual(sparse.cells, snapshot.cells);
assert.equal(sparse.moves, snapshot.moves);
assert.equal(sparse.line, snapshot.line);
assert.equal(sparse.redo(), true);
assert.equal(sparse.soldierCount, 0);
assert.equal(sparse.reset(), true);
assert.equal(sparse.base, 'army');
assert.equal(sparse.soldierCount, Infinity);
assert.equal(sparse.has(987654321, 0), true);
assert.equal(sparse.undo(), true);
assert.equal(sparse.base, 'empty');
assert.equal(sparse.redo(), true);
assert.equal(sparse.base, 'army');

const boundary = new Game();
boundary.clear();
boundary.toggle(Number.MAX_SAFE_INTEGER, 0);
boundary.toggle(Number.MAX_SAFE_INTEGER - 1, 0);
assert.deepEqual(boundary.legalMoves(Number.MAX_SAFE_INTEGER, 0), [{ x: Number.MAX_SAFE_INTEGER - 2, y: 0 }]);
assert.equal(boundary.move(Number.MAX_SAFE_INTEGER, 0, Number.MAX_SAFE_INTEGER + 1, 0), false);
assert.equal(new Game().undo(), false);
assert.equal(new Game().redo(), false);
assert.equal(new Game().reset(), false);

console.log('Game checks passed: infinite army, all move directions, validation, editing, line, undo/redo, reset/clear.');
